### PR TITLE
Enhanced content in communities pages.

### PR DESCRIPTION
**Pull request by jimtyhurst**
* Added text to the 3 communities pages to get word count up to 1,000-1,500 range per page for SEO.
* `gigs` => `projects` in index.js at the top and in about.js.
* Fixed lint errors.

### CODE REVIEW

**Comment by jimtyhurst** [comment]
# Suggestion
Put the call to action (`Sign up to try it!` header down to the `Sign me up!` button) higher on the page, between the images and the new content. Leave a `Sign me up!` button at the bottom of the page too.

**Comment by jimtyhurst** [comment]
# Suggestion
Move the road map and implementation content to a separate page. So put `Evolution and Road Map` and `Behind the Scenes` and maybe `Community First, Then Everything Else` on a separate page, e.g. the `About` page, `FAQ` page, or a blog post.

**Comment by jimtyhurst** [comment]
# Suggestion
Expand all of the contractions. For example,

- `We're` => `We are`
- `they're` => `they are`
- `can't` => `cannot`
- etc.

**Review by craigfisk — APPROVED** [review]
- Agree about separating out the repetitive parts. Think we should leave that as it is for now.
- Agree about the contractions. Will check those.
- Thanks for checking subtitle capitalizations.

**Comment by craigfisk** [comment]
See comments. Looks OK for now. Will deal with contractions.

**Pull request merged**
